### PR TITLE
Incidence inconsistence def

### PR DESCRIPTION
**Pull request by ftmartins**
The definition of incidence_matrix in localization_utils.py is inconsistent with that of the CL class, where it's its inverse.

In CL, incidence matrix (Number of Nodes, Number of Edges) while for localization_utils.py, it's dotted onto partition (NN) to produce an array (NE) so that would require it to be (NE, NN).

### CODE REVIEW

**Comment by maguzj** [comment]
You are right, it is written into the description of the function itself. The matrix must be the transpose of the incidence_matrix given by the network.

It would be better to simply change the name of the argument, instead of transposing every time you call the function.

**Review by maguzj — CHANGES_REQUESTED** [review]
It would be better to change the name to a more appropriate or suggestive one, rather than transposing for every call

**Comment by ftmartins** [comment]
get_boundary now takes transpose_incidence_matrix instead of transposing the matrix for every call

**Review by maguzj — APPROVED** [review]

**Comment by maguzj** [comment]
👍🏽

**Pull request merged**
